### ISSUE TITLE
Policy lacks the 'watch' permission for logs

### ISSUE THREAD

**Issue by lopf** [rancher/rancher-selinux#32]
### Test setup
- Kubernetes 1.25.13 RKE2 cluster on custom Rocky Linux 9.2 nodes
- RPMs: rke2-selinux-0.15-1.el8.noarch / rancher-selinux-0.3~rc1-2.el9.noarch
- SELinux in 'Enforcing mode'
- RKE2 with `selinux: true`
- kube-logging Operator 4.4.1 (fluentbit 2.1.8)
- FluentbitAgent CR:
```yaml
apiVersion: logging.banzaicloud.io/v1beta1
kind: FluentbitAgent
metadata:
  # Use the name of the logging resource
  name: logging-operator
  namespace: kube-logging
spec:
  security:
    securityContext:
      seLinuxOptions:
        type: rke_logreader_t
```

### Result

Fluentbit stdout:
```
[2023/11/06 21:31:58] [error] [/src/fluent-bit/plugins/in_tail/tail_fs_inotify.c:147 errno=13] Permission denied
[2023/11/06 21:31:58] [error] [input:tail:tail.0] inode=67407509 cannot register file /var/log/containers/rke2-canal-qtln6_kube-system_calico-node-390e4f52e309f4d2950e530bdc010c1b35bab0bd2f1fa513b11a1f1d5e966126.log
```

SELinux deny messages:
```
time->Mon Nov  6 22:08:01 2023
type=PROCTITLE msg=audit(1699304881.069:5976): proctitle=2F666C75656E742D6269742F62696E2F666C75656E742D626974002D63002F666C75656E742D6269742F6574632D6F70657261746F722F666C75656E742D6269742E636F6E66
type=PATH msg=audit(1699304881.069:5976): item=0 name="/var/log/pods/kube-system_rke2-snapshot-validation-webhook-7f955488ff-vh4vb_54ad6459-f3f1-4146-95a5-92dead276341/rke2-snapshot-validation-webhook/3.log" inode=35319943 dev=fd:00 mode=0100640 ouid=0 ogid=0 rdev=00:00 obj=system_u:object_r:container_log_t:s0 nametype=NORMAL cap_fp=0 cap_fi=0 cap_fe=0 cap_fver=0 cap_frootid=0
type=CWD msg=audit(1699304881.069:5976): cwd="/"
type=SYSCALL msg=audit(1699304881.069:5976): arch=c000003e syscall=254 success=no exit=-13 a0=1c a1=7faa21272000 a2=c806 a3=5d items=1 ppid=9152 pid=9206 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="flb-pipeline" exe="/fluent-bit/bin/fluent-bit" subj=system_u:system_r:rke_logreader_t:s0:c568,c795 key=(null)
type=AVC msg=audit(1699304881.069:5976): avc:  denied  { watch } for  pid=9206 comm="flb-pipeline" path="/var/log/pods/kube-system_rke2-snapshot-validation-webhook-7f955488ff-vh4vb_54ad6459-f3f1-4146-95a5-92dead276341/rke2-snapshot-validation-webhook/3.log" dev="dm-0" ino=35319943 scontext=system_u:system_r:rke_logreader_t:s0:c568,c795 tcontext=system_u:object_r:container_log_t:s0 tclass=file permissive=0
```
